


console.log ("JavaScript Alert \n \n \n hello... i can run JS through my browser console")

alert(' JavaScript Alert \n \n \n Error!  Please enter your valid password')

alert("JavaScript Alert \n \n Welcome to JS land... \n \n Happy Coding!    ")


alert("JavaScript Alert \n \n Welcome to JS land...     ")


alert(" \n \n Happy Coding! \n \n Prevent this page creating additional dialogs   ")



